name: Tests

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout glTF Sample Models
        uses: actions/checkout@v2
        with:
          repository: KhronosGroup/glTF-Sample-Models
          path: glTF-Sample-Models

      - name: Tests
        run: cargo test --all --all-features --release
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-features
